### ISSUE TITLE
Types Required for react typescript project

### ISSUE THREAD

**Issue by cabdallah-link** [nojsja/react-nojsja#11]
Hello

It's not working with a reactjs tsx project it requires types to be declared or installed which is not available in your case

**Comment by nojsja** [comment]
> Hello
> 
> It's not working with a reactjs tsx project it requires types to be declared or installed which is not available in your case

typescript support soon.

**Comment by nojsja** [comment]
The component can now be used in ts project with types support, install `editable-tree-antd ` 1.1.0 version.
