### ISSUE TITLE
Load child element from database when click expanded button ( customize the expandable feature)

### ISSUE THREAD

**Issue by Rik993** [nojsja/react-nojsja#13]
Hello nojsja,

I am struggling to customize the node expandable feature. So please help me to continue the development by answering the following questions?

1. How to get the expanded element Id from the parent node?
2. When expanding a parent node, how to load all the child nodes from the database by sending the parent node Id to the database?
3. How to write a custom message if child nodes are empty after being retrieved from the database?
4. How to load minimized parent nodes when data initially loads?
5. How to hide 'AddSisterNode' , 'AddSubNode' icons?
6. How to remove 'colon(:)' near to the NodeName?

Thanks.

**Comment by nojsja** [comment]
I will think about those questions and give you some advices soon.

**Comment by nojsja** [comment]
OR maybe a version upgrade.

**Comment by Rik993** [comment]
Ok, we are waiting for your detailed advice.

> I will think about those questions and give you some advices soon.

**Comment by nojsja** [comment]
New features supported, check out version - `1.1.1`
![image](https://user-images.githubusercontent.com/19613878/149666778-afe52c10-e1c7-47eb-9a72-74ea945e12be.png)
