### ISSUE TITLE
Font Size

### ISSUE THREAD

**Issue by Aliber009** [nojsja/react-nojsja#9]
Hello where I can change the font size please and the file Icone please

**Comment by nojsja** [comment]
> Hello where I can change the font size please and the file Icone please

Check the rendered dom element and write your own style to overwrite the default antd style. If you want to use other icons, read [antd  tree doc](https://ant.design/components/tree/). Fork my code, change the EditableTree source code, compile, submit to npm.

**Comment by Aliber009** [comment]
thanks I see you are using pure react dom instead of jsx which is hard for me to understand and modify , in your node modules
